---
title: "Hamiltonian Monte Carlo"
author: "梅崎直也"
date: "2018/8/16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

参考文献
https://drive.google.com/file/d/0Bw-J75fYQ33NaWxjb2VwMDU4cjg/view

## ハミルトニアンとは
関係ない物理の話。
$N$個の粒子、それぞれ位置$x_i$と運動量$p_i$をもつ。
粒子はハミルトン方程式
$$
\frac{dx_i}{dt}=\frac{\partial H}{\partial p_i}\\
\frac{dp_i}{dt}=-\frac{\partial H}{\partial x_i}
$$
にしたがって運動する。
ここで$H$はハミルトニアンと呼ばれる$x, p$を引数にもつ関数で、これが物理的な設定を規定する。

### 例
$H=\frac{p^2}{2}$のとき、
$$
\frac{\partial H}{\partial p}=p\\
\frac{\partial H}{\partial x}=0
$$
であり、ハミルトン方程式は
$$
\frac{dx}{dt}=p\\
\frac{dp}{dt}=0
$$
となる。

初期値$x_0, p_0$に対する解は
$$
p=p_0\\
x=p_0t+x_0
$$
である。

上の方程式を二階の微分方程式に直すと
$$
\frac{d^2 x}{dt^2}=0
$$
である。
これは質量$1$の等速直線運動を表す。
この解をハミルトニアンに代入すると
$$
H=\frac{p_0^2}{2}
$$
となり、これは$t$によらず一定である。
いわゆる運動エネルギーを表している。

### ポテンシャルのある例
$H=\frac{p^2}{2}+V$のとき、
$$
\frac{\partial H}{\partial p}=p+\frac{\partial V}{\partial p}\\
\frac{\partial H}{\partial x}=\frac{\partial V}{\partial x}
$$
であり、ハミルトン方程式は
$$
\frac{dx}{dt}=p+\frac{\partial V}{\partial p}\\
\frac{dp}{dt}=-\frac{\partial V}{\partial x}
$$
である。

特に$V$が$p$に依存しない場合を考えると、ハミルトン方程式は
$$
\frac{dx}{dt}=p\\
\frac{dp}{dt}=-\frac{\partial V}{\partial x}
$$
であり、これを二階の微分方程式に直すと
$$
\frac{d^2 x}{dt^2}=-\frac{\partial V}{\partial x}
$$
である。

例えば$V=-gx$なら自由落下を表す。
この場合、初期値$x_0, p_0$に対する解は
$$
p=gt+p_0\\
x=x_0+\frac{1}{2}gt^2+p_0t
$$
である。
これを$H$に代入すると、
$$
\frac{(gt+p_0)^2}{2}-gx=\frac{1}{2}p_0^2-gx_0
$$
でありこれは$t$によらず一定である。

$V=\frac{x^2}{2}$なら単振動。
ハミルトン方程式は
$$
\frac{dx}{dt}=p\\
\frac{dp}{dt}=-x
$$
であり、これを二階の微分方程式に直すと
$$
\frac{d^2 x}{dt^2}=-x
$$
この場合、初期値$x_0, p_0$に対する解は
$$
x=\sqrt{x_0^2+p_0^2}\cos(t+b)\\
p=\sqrt{x_0^2+p_0^2}\sin(t+b)\\
\frac{x_0}{\sqrt{x_0^2+p_0^2}}=\cos(b)\\
\frac{p_0}{\sqrt{x_0^2+p_0^2}}=\sin(b)\\
$$
である。
これを$H$に代入すると、
$$
\frac{p^2}{2}+\frac{x^2}{2}=\frac{p_0^2}{2}+\frac{x_0^2}{2}
$$
でありこれは$t$によらず一定である。


## 重要な性質
$(x,p)$空間の確率密度関数$q(x,p)$が$H$だけの関数である、つまりある$r(y)$が存在して$q(x,p)=r(H(x.p))$となっているとする。
このとき、ハミルトン方程式による状態変化について定常分布になっている。

つまり初期値$(x(0), p(0))$から定まるハミルトン方程式の解の$t=T$での値を$(x(T), q(T))$とする。
このとき、$f:(x(0), q(0)) \to (x(T), q(T))$の定常分布が$q(x,p)$である。

事後分布からのサンプリング
運動量$p$を導入する必要がある。
事後分布の$\log$をポテンシャルにする。
$$
H(x,p) = \sum\frac{p_i^2}{2}-\log p(x\mid D)
$$
とする。
確率密度
$$
q(x,p)=C\exp(-H(x,p))\\
=C\exp(-\sum\frac{p_i^2}{2})p(x\mid D)
$$
とすると、これは上で述べたことからハミルトン方程式の解から定まる写像の定常分布になる。

例。
単振動の例、正規分布

実際には、

- ハミルトン方程式に基づいた時間発展
- $p$のギブスサンプリング

を交互に行う。

詳細釣り合い条件について。
$t$は常に増加方向なので、そのままでは成り立たない。
運動量の更新までまとめると満たされる。

二つの重要な性質

- $H(x,p)=H(f(x,p))$
- $f$のヤコビアンは$1$に等しい

このことから、$q(x,p)=r(H(x,p))$が任意の$r$について定常分布になることが示せる。

$T$の大きさをどのようにとるか？
NUTSというアルゴリズムで決める。

$t$を離散化する。
離散的にうまく微分方程式をとくためにリープフロッグ法を使う。

わざわざ$f$を導入するのはなぜか？
$f=\exp$とすれば$p$の分布が正規分布になる。

$p$を変化させるのはなぜか？

詳細釣り合い条件を満たすようにする。
$H(x,p)$一定の部分に制限した分布の乱数は生成できる。
一方で、目的の分布全体を取るためには$p$を動かす必要がある。

## リープフロッグ法
微分方程式を数値的にとくアルゴリズム。

- 精度高い
- エネルギー保存する（ハミルトニアンを一定に保つ）

$$
\frac{dv}{dt}=f(x)\\
\frac{dx}{dt}=v
$$

の形の微分方程式を数値的に解く。
アルゴリズム
$$
x_i=x_{i-1}+v_{i-1/2}\delta t\\
a_i=f(x_i)\\
v_{i+1/2}=v_{i-1/2}+a_i\delta t
$$
とする。
ここから$v_i=\frac{1}{2}(v_{i+1/2}+v_{i-1/2})$とする。
つまり
$$
v_{i+1}=v_i+\frac{1}{2}(a_i+a_{i+1})\delta t
$$
となる。
